#!/usr/bin/env bash
# infra/templates/setup.sh
#
# Run from inside a NEW app repo directory to wire it up for this local CI
# system: copies the fastlane/ and .gitea/ templates in, writes app-specific
# config, updates .gitignore, and (optionally) creates the repo in the local
# Gitea instance and adds it as a git remote.
#
# Canonical location on the Mac: ~/infra/templates/setup.sh (kept in sync
# with this repo's infra/templates/ by infra/scripts/02_install_runner.sh).
# This script locates its own sibling fastlane/ and .gitea/ directories via
# its own path, so it works correctly whether run from ~/infra/templates or
# straight out of a checkout of this repo.
#
# Usage (flags, all optional -- omitted ones are prompted for):
#   setup.sh --bundle-id com.example.myapp --scheme MyApp --device-id <UDID> \
#            [--no-gitea-repo] [--gitea-repo-name myapp]
#
# Idempotent: re-running updates the copied templates and env files without
# duplicating .gitignore entries or failing if the Gitea repo/remote already
# exist.
set -euo pipefail

SCRIPT_DIR="$(cd -- "$(dirname -- "${BASH_SOURCE[0]}")" &>/dev/null && pwd)"
TARGET_DIR="$(pwd)"

APP_IDENTIFIER=""
SCHEME=""
DEVICE_ID=""
CREATE_GITEA_REPO=1
GITEA_REPO_NAME="$(basename "${TARGET_DIR}")"

usage() {
  cat <<EOF
Usage: $0 [--bundle-id ID] [--scheme NAME] [--device-id UDID]
          [--gitea-repo-name NAME] [--no-gitea-repo]

Run from inside the target app repo's root directory.
EOF
}

while [ "$#" -gt 0 ]; do
  case "$1" in
    --bundle-id) APP_IDENTIFIER="$2"; shift 2 ;;
    --scheme) SCHEME="$2"; shift 2 ;;
    --device-id) DEVICE_ID="$2"; shift 2 ;;
    --gitea-repo-name) GITEA_REPO_NAME="$2"; shift 2 ;;
    --no-gitea-repo) CREATE_GITEA_REPO=0; shift ;;
    -h|--help) usage; exit 0 ;;
    *) echo "Unknown argument: $1" >&2; usage; exit 1 ;;
  esac
done

# Prompt interactively for anything not passed as a flag (only if attached
# to a terminal -- non-interactive callers like 05_verify_e2e.sh must pass
# all three via flags).
if [ -z "${APP_IDENTIFIER}" ] && [ -t 0 ]; then
  read -r -p "Bundle identifier (e.g. com.example.myapp): " APP_IDENTIFIER
fi
if [ -z "${SCHEME}" ] && [ -t 0 ]; then
  read -r -p "Xcode scheme name: " SCHEME
fi
if [ -z "${DEVICE_ID}" ] && [ -t 0 ]; then
  read -r -p "Physical device UDID (blank ok, can set later): " DEVICE_ID
fi

if [ -z "${APP_IDENTIFIER}" ] || [ -z "${SCHEME}" ]; then
  echo "ERROR: --bundle-id and --scheme are required." >&2
  usage
  exit 1
fi

echo "==> Target repo: ${TARGET_DIR}"

if [ ! -d "${TARGET_DIR}/.git" ]; then
  echo "==> No .git found -- initializing a new repo here."
  git init "${TARGET_DIR}" >/dev/null
fi

echo "==> Copying fastlane/ template ..."
mkdir -p "${TARGET_DIR}/fastlane"
cp -f "${SCRIPT_DIR}/fastlane/Fastfile" "${TARGET_DIR}/fastlane/Fastfile"
cp -f "${SCRIPT_DIR}/fastlane/Appfile" "${TARGET_DIR}/fastlane/Appfile"
cp -f "${SCRIPT_DIR}/fastlane/Matchfile" "${TARGET_DIR}/fastlane/Matchfile"
cp -f "${SCRIPT_DIR}/fastlane/Gymfile" "${TARGET_DIR}/fastlane/Gymfile"
# Fastfile/Appfile/Matchfile/Gymfile are always overwritten with the latest
# template (they're app-agnostic and env-driven -- no per-app edits expected
# to survive). If you *do* customize one by hand, remove it from this list.

echo "==> Copying .gitea/workflows/ci.yml template ..."
mkdir -p "${TARGET_DIR}/.gitea/workflows"
cp -f "${SCRIPT_DIR}/.gitea/workflows/ci.yml" "${TARGET_DIR}/.gitea/workflows/ci.yml"

echo "==> Writing fastlane/.env.default (safe to commit -- placeholders only) ..."
cat > "${TARGET_DIR}/fastlane/.env.default" <<EOF
# Generated by infra/templates/setup.sh. Placeholders only, safe to commit.
# Real values live in fastlane/.env (gitignored) and/or the runner's host
# environment -- see infra/.env.default and infra/INFRA.md.
APP_IDENTIFIER=
SCHEME=
DEVICE_ID=
ASC_KEY_ID=
ASC_ISSUER_ID=
ASC_KEY_PATH=
MATCH_PASSWORD=
MATCH_GIT_URL=
EOF

# Sets KEY=VALUE in a .env-style file, replacing an existing line for that
# key in place (preserving any other lines/secrets a user added by hand) or
# appending a new one. Keeps re-runs idempotent without clobbering manual
# additions like ASC_* / MATCH_* that a user chose to keep per-repo.
set_env_var() {
  local file="$1" key="$2" value="$3"
  touch "${file}"
  if grep -q "^${key}=" "${file}"; then
    # BSD sed (macOS) requires an argument to -i; use a throwaway backup ext.
    sed -i '' -e "s|^${key}=.*|${key}=${value}|" "${file}"
  else
    echo "${key}=${value}" >> "${file}"
  fi
}

echo "==> Writing fastlane/.env (gitignored -- real per-app values) ..."
if [ ! -f "${TARGET_DIR}/fastlane/.env" ]; then
  cat > "${TARGET_DIR}/fastlane/.env" <<'EOF'
# Generated by infra/templates/setup.sh -- gitignored, do not commit.
# App-specific values managed by setup.sh below this line. Shared secrets
# (ASC_*, MATCH_*) are expected to come from the runner's own host
# environment; feel free to add them here too if you'd rather keep them
# per-repo instead -- setup.sh re-runs will not touch unrecognized lines.
EOF
fi
set_env_var "${TARGET_DIR}/fastlane/.env" "APP_IDENTIFIER" "${APP_IDENTIFIER}"
set_env_var "${TARGET_DIR}/fastlane/.env" "SCHEME" "${SCHEME}"
set_env_var "${TARGET_DIR}/fastlane/.env" "DEVICE_ID" "${DEVICE_ID}"

# Mirror the same three values at the repo root as a convenience .env for
# any tooling (outside fastlane) that expects one there.
echo "==> Writing repo-root .env (gitignored) ..."
if [ ! -f "${TARGET_DIR}/.env" ]; then
  echo "# Generated by infra/templates/setup.sh -- gitignored, do not commit." \
    > "${TARGET_DIR}/.env"
fi
set_env_var "${TARGET_DIR}/.env" "APP_IDENTIFIER" "${APP_IDENTIFIER}"
set_env_var "${TARGET_DIR}/.env" "SCHEME" "${SCHEME}"
set_env_var "${TARGET_DIR}/.env" "DEVICE_ID" "${DEVICE_ID}"

echo "==> Updating .gitignore ..."
GITIGNORE="${TARGET_DIR}/.gitignore"
touch "${GITIGNORE}"
add_ignore() {
  grep -qxF "$1" "${GITIGNORE}" || echo "$1" >> "${GITIGNORE}"
}
add_ignore ".env"
add_ignore "fastlane/.env"
add_ignore "fastlane/report.xml"
add_ignore "fastlane/test_output/"
add_ignore "build/"
add_ignore "*.ipa"
add_ignore "*.dSYM.zip"
add_ignore ".DS_Store"

if [ "${CREATE_GITEA_REPO}" -eq 1 ]; then
  GITEA_INSTANCE_URL="${GITEA_INSTANCE_URL:-http://localhost:3000}"
  if [ -z "${GITEA_TOKEN:-}" ] || [ -z "${GITEA_ADMIN_USER:-}" ]; then
    echo "==> Skipping Gitea repo creation: set GITEA_TOKEN and GITEA_ADMIN_USER" \
         "in your shell env to enable this (see infra/.env.default). Pass" \
         "--no-gitea-repo to silence this message."
  else
    echo "==> Ensuring repo '${GITEA_REPO_NAME}' exists in Gitea ..."
    http_status="$(curl -s -o /dev/null -w '%{http_code}' \
      -H "Authorization: token ${GITEA_TOKEN}" \
      "${GITEA_INSTANCE_URL}/api/v1/repos/${GITEA_ADMIN_USER}/${GITEA_REPO_NAME}")"
    if [ "${http_status}" = "200" ]; then
      echo "    Repo already exists on Gitea -- skipping creation."
    else
      curl -s -X POST \
        -H "Authorization: token ${GITEA_TOKEN}" \
        -H "Content-Type: application/json" \
        -d "{\"name\": \"${GITEA_REPO_NAME}\", \"private\": true, \"auto_init\": false}" \
        "${GITEA_INSTANCE_URL}/api/v1/user/repos" \
        | jq -e '.id' >/dev/null \
        && echo "    Created repo '${GITEA_REPO_NAME}' on Gitea." \
        || echo "    WARNING: repo creation call did not return an id -- check manually."
    fi

    REMOTE_URL="${GITEA_INSTANCE_URL}/${GITEA_ADMIN_USER}/${GITEA_REPO_NAME}.git"
    if git -C "${TARGET_DIR}" remote get-url gitea >/dev/null 2>&1; then
      git -C "${TARGET_DIR}" remote set-url gitea "${REMOTE_URL}"
      echo "    Updated existing 'gitea' remote -> ${REMOTE_URL}"
    else
      git -C "${TARGET_DIR}" remote add gitea "${REMOTE_URL}"
      echo "    Added 'gitea' remote -> ${REMOTE_URL}"
    fi
  fi
fi

cat <<EOF

==> Setup complete for ${GITEA_REPO_NAME}.

  APP_IDENTIFIER = ${APP_IDENTIFIER}
  SCHEME         = ${SCHEME}
  DEVICE_ID      = ${DEVICE_ID:-<not set -- tests will fall back to simulator>}

Next steps:
  1. Review/commit fastlane/, .gitea/workflows/ci.yml, fastlane/.env.default,
     and .gitignore. fastlane/.env and .env are gitignored -- do not commit.
  2. If a 'gitea' remote was added: git push gitea main
  3. Confirm the Actions run at:
     ${GITEA_INSTANCE_URL:-http://localhost:3000}/${GITEA_ADMIN_USER:-<user>}/${GITEA_REPO_NAME}/actions

EOF
